### ISSUE TITLE
Visualization of tracked features and trajectory

### ISSUE THREAD

**Issue by stephen9999999** [jpl-x/x_multi_agent_ros#2]
Hi, thanks for your code.
When I run the code, I cannot find the estimated trajectory topic and tracked feature image topic, therefore, I cannot add them in the RVIZ for visualization.  Could you add the visualization of estimated path and the tracked image features as shown in your paper and video? Thank you.

**Comment by viciopoli01** [comment]
This solves the visualization issue https://github.com/jpl-x/x_multi_agent/issues/4 .
