### ISSUE TITLE
run issue

### ISSUE THREAD

**Issue by wanghuan0812** [jpl-x/x_multi_agent_ros#5]
In docker environment,When I run the command：" roslaunch x_vio_ros vio_multi_thermal.launch nr:=1"and"rosbag play mars_yard_duo_tf.bag --clock -s 9 -u 41 -r 0.1"，Terminal display:" [warning] Closest state request too far in the past. Increase buffer size.Timestamp : 1549607581.9883764. Oldest state in buffer : 1549607582.0334387".
why?how to solve? Thanks...

**Comment by viciopoli01** [comment]
Hi @wanghuan0812 ,

Do you see this warning continually or just a few times?

Best,
Vincenzo

**Comment by wanghuan0812** [comment]
> Hi @wanghuan0812 ,
> 
> Do you see this warning continually or just a few times?
> 
> Best, Vincenzo

sorry for the delay, my issue was solved . It 's a mismatch between the X library and the ROS wrapper. Thanks a lot for your code.

**Comment by wanghuan0812** [comment]
Dear sir ,
There is another issue when I run the code with my own bag ,How do I get the Initial state estimates which is the first part in the yaml.  such as p, v, q and sigma_dp …...

Thanks  a lot!

**Comment by viciopoli01** [comment]
Hi @wanghuan0812 , 

p, v, q are the initial position, velocity, and rotation quaternion. You can set these values with the initial values from your bag file or just init them to 0. When evaluating against the ground truth, align your estimate with the ground truth.

What was the mismatch between X and the ROS? 
Other users can have the same issue. Thanks.

Best,
Vincenzo

**Comment by wanghuan0812** [comment]
> Hi @wanghuan0812 ,
> 
> p, v, q are the initial position, velocity, and rotation quaternion. You can set these values with the initial values from your bag file or just init them to 0. When evaluating against the ground truth, align your estimate with the ground truth.
> 
> What was the mismatch between X and the ROS? Other users can have the same issue. Thanks.
> 
> Best, Vincenzo

Thank you for your reply.
I means that before complie the code  must check if the flags in the CMakeLists of the ROS project and the ones you used for building the X library are the same ,The mismatch between the enabled options can be problematic. As you said before.

**Comment by wanghuan0812** [comment]
Dear sir ,
when I run the code with my own bag. As shown in the figure,It feels like the photometric calibration is not working.why?how to solve?My device is a mobile vehicle with flir_tau2.
best,
![image](https://github.com/jpl-x/x_multi_agent_ros/assets/104182536/60f8bf81-1471-4dc5-b9cd-08371814ac38)
![trajectory](https://github.com/jpl-x/x_multi_agent_ros/assets/104182536/18a08217-110f-4f77-9ca7-755f4787d35d)

**Comment by viciopoli01** [comment]
Hi, would you mind to open a new issue regarding the photometric calibration? Also, this issue should be for the [x_multi_agent](https://github.com/jpl-x/x_multi_agent) and not for its ros wrapper.
Thanks

**Comment by viciopoli01** [comment]
Since you can now run the code we can close this issue.
